-   id: cblack
    name: cblack
    description: 'Black: The uncompromising Python code formatter'
    entry: cblack
    language: python
    language_version: python3
    require_serial: true
    types: [python]
